project_id = "beeurnwjijmqdazrtlgu"

[functions.generate-itinerary]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.generate-trip-suggestions]
verify_jwt = true

[functions.demo-login]
verify_jwt = false

[functions.search-flights]
verify_jwt = false

[functions.parse-travel-document]
enabled = true
verify_jwt = true
import_map = "./functions/parse-travel-document/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/parse-travel-document/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/parse-travel-document/*.html" ]
